// The gate's own failure modes.
//
// The one that matters: `.cache.json` is not committed, so a clean clone — which
// is what CI runs — used to leave symbol citations unchecked and still exit 0.
// A gate that reports Green without having checked is worse than no gate, and
// nothing about it looks broken.

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { extract } from '../scripts/extract.mjs'
import { OUT_DIR } from '../scripts/lib/scan.mjs'
import { run } from '../scripts/check.mjs'

const DOC = `---
scope: .
---

# Fixture

\`simboloQueNoExiste\` is cited here and declared nowhere.

<!-- @map:start — generated by codegraph. Do not edit. -->
<!-- @map:end -->
`

function repo() {
  const dir = mkdtempSync(join(tmpdir(), 'codegraph-gate-'))
  mkdirSync(join(dir, 'src'))
  writeFileSync(join(dir, 'src', 'money.ts'), '/** Formats. */\nexport function formatMoney(n) { return n }\n')
  writeFileSync(join(dir, 'CLAUDE.md'), DOC)
  return dir
}

const cites = (findings) => findings.some((f) => f.msg.includes('simboloQueNoExiste'))
const unchecked = (findings) => findings.some((f) => f.msg.includes('were NOT checked'))

test('a citation to a symbol that does not exist is a finding', () => {
  const dir = repo()
  try {
    extract(dir, join(dir, OUT_DIR), { full: true })
    assert.ok(cites(run(dir).findings))
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
})

test('the citation check survives a clean clone, where .cache.json is absent', () => {
  const dir = repo()
  try {
    extract(dir, join(dir, OUT_DIR), { full: true })
    rmSync(join(dir, OUT_DIR, '.cache.json')) // never committed — see SKILL.md
    assert.ok(cites(run(dir).findings), 'index.json must carry the identifiers')
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
})

test('a gate that could not check says so instead of passing', () => {
  const dir = repo()
  try {
    const { findings } = run(dir) // extract never ran
    assert.ok(unchecked(findings), 'silence here is indistinguishable from a pass')
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
})

test('a malformed language table costs that language, never the run', () => {
  const dir = repo()
  try {
    // The override lives beside the index: one folder is the whole footprint.
    mkdirSync(join(dir, OUT_DIR), { recursive: true })
    writeFileSync(
      join(dir, OUT_DIR, 'languages.json'),
      JSON.stringify({ broken: { exts: ['.zz'], decls: [{ re: '^(unclosed[', name: 1 }] } })
    )
    const { index, problems } = extract(dir, join(dir, OUT_DIR), { full: true })
    assert.equal(problems.length, 1)
    assert.match(problems[0], /broken/)
    assert.ok(index.symbols.length, 'the other languages still indexed')
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
})
