// The doc pyramid: finding the files, reading their frontmatter, and working
// out which is a surface and which is a domain.

import { readdirSync, readFileSync, existsSync } from 'node:fs'
import { join, relative, sep, dirname } from 'node:path'

const DOC_NAMES = ['CLAUDE.md', 'AGENTS.md']
const SKIP = new Set(['node_modules', '.git', 'dist', 'build', 'docs-graph', 'graphify-out', '.dart_tool'])

/** The marker pair. Hand-placed once per file; the generator only ever writes
 *  between them, and refuses to act when they are absent. */
export const MARK_START = '<!-- @map:start — generated by codegraph. Do not edit. -->'
/** Closes the pair. Everything between the two is rewritten on every --write. */
export const MARK_END = '<!-- @map:end -->'
const START_RE = /<!--\s*@map:start[\s\S]*?-->/
const END_RE = /<!--\s*@map:end\s*-->/

/** One convention per repo, never both: if AGENTS.md is already in use, that is
 *  the name; otherwise CLAUDE.md. Mixing the two splits the pyramid in half. */
export function conventionOf(root) {
  const found = findDocFiles(root)
  const agents = found.filter((f) => f.endsWith('AGENTS.md')).length
  const claude = found.filter((f) => f.endsWith('CLAUDE.md')).length
  if (agents && claude) return { name: 'CLAUDE.md', mixed: true }
  return { name: agents ? 'AGENTS.md' : 'CLAUDE.md', mixed: false }
}

/** Every doc file in the tree, repo-relative and sorted, both conventions. */
export function findDocFiles(root) {
  const out = []
  const visit = (dir) => {
    let entries
    try {
      entries = readdirSync(dir, { withFileTypes: true })
    } catch {
      return
    }
    for (const e of entries) {
      if (SKIP.has(e.name) || (e.name.startsWith('.') && e.isDirectory())) continue
      const full = join(dir, e.name)
      if (e.isDirectory()) visit(full)
      else if (DOC_NAMES.includes(e.name)) out.push(relative(root, full).split(sep).join('/'))
    }
  }
  visit(root)
  return out.sort()
}

/**
 * Frontmatter, hand-parsed. Only three keys are accepted; an unknown key is a
 * finding rather than a crash, because a doc file with a typo in it should
 * still be readable.
 */
export function parseFrontmatter(text) {
  const lines = text.split('\n')
  if (lines[0]?.trim() !== '---') {
    return { data: null, body: text, bodyOffset: 0, problems: ['missing frontmatter'] }
  }
  const end = lines.findIndex((l, i) => i > 0 && l.trim() === '---')
  if (end < 0) {
    return { data: null, body: text, bodyOffset: 0, problems: ['unterminated frontmatter'] }
  }

  const data = {}
  const problems = []
  let currentList = null

  for (const raw of lines.slice(1, end)) {
    if (!raw.trim() || raw.trim().startsWith('#')) continue
    const item = raw.match(/^\s+-\s+(.*)$/)
    if (item && currentList) {
      currentList.push(item[1].trim().replace(/^["']|["']$/g, ''))
      continue
    }
    const kv = raw.match(/^([A-Za-z_]+):\s*(.*)$/)
    if (!kv) {
      problems.push(`cannot parse frontmatter line: ${raw.trim().slice(0, 60)}`)
      continue
    }
    const [, k, v] = kv
    if (!['scope', 'read_before', 'ripples_to'].includes(k)) {
      problems.push(`unknown frontmatter key: ${k}`)
      currentList = null
      continue
    }
    if (v.trim()) {
      data[k] = v.trim().replace(/^["']|["']$/g, '')
      currentList = null
    } else {
      data[k] = []
      currentList = data[k]
    }
  }

  return {
    data,
    body: lines.slice(end + 1).join('\n'),
    bodyOffset: end + 1,
    problems,
  }
}

/** A doc file with its frontmatter parsed and its own directory resolved. */
export function readDoc(root, relPath) {
  const text = readFileSync(join(root, relPath), 'utf8')
  const parsed = parseFrontmatter(text)
  const dir = dirname(relPath).replace(/\\/g, '/')
  return { path: relPath, text, dir: dir === '.' ? '.' : dir, ...parsed }
}

/** A surface is structural, never a judgement call: a doc file with no doc file
 *  above it. That keeps the layer assignment from drifting with opinion. */
export function classify(docs) {
  const dirs = new Set(docs.map((d) => d.dir))
  return docs.map((d) => {
    let parent = null
    let cur = d.dir
    while (cur !== '.' && cur !== '') {
      cur = cur.includes('/') ? cur.slice(0, cur.lastIndexOf('/')) : '.'
      if (dirs.has(cur)) { parent = cur; break }
    }
    return { ...d, parent, layer: parent ? 'domain' : 'surface' }
  })
}

/** Body lines, excluding the generated block. Generated metadata does not
 *  compete with prose for the budget — the budget exists to cap what a human
 *  wrote and a reader must read. */
export function bodyLineCount(body) {
  const start = body.search(START_RE)
  if (start < 0) return body.split('\n').filter((l) => l.trim()).length
  const endMatch = body.match(END_RE)
  const end = endMatch ? body.indexOf(endMatch[0]) + endMatch[0].length : body.length
  const without = body.slice(0, start) + body.slice(end)
  return without.split('\n').filter((l) => l.trim()).length
}

/** The text with `block` between the markers, or null when there are none.
 *  Returning null rather than appending is what stops the generator from
 *  deciding where a block belongs. */
export function splice(text, block) {
  const start = text.match(START_RE)
  const end = text.match(END_RE)
  if (!start || !end) return null // markers are hand-placed; never invent them
  const from = text.indexOf(start[0])
  const to = text.indexOf(end[0]) + end[0].length
  if (to < from) return null
  return text.slice(0, from) + block + text.slice(to)
}

/** Whether a `ripples_to` target is real. A declared edge to a path that does
 *  not exist becomes a finding, never a generated backlink. */
export function pathExists(root, p) {
  return existsSync(join(root, p))
}
